"""EngiTrace AI — Compliance Findings Endpoints (Phase 4)"""

from typing import List, Optional
from fastapi import APIRouter, Depends, Query, HTTPException, status
from sqlalchemy.orm import Session

from backend.app.database import get_db
from backend.app.schemas.findings import FindingResponse, FindingUpdate
from backend.app.repositories.finding_repo import FindingRepository

router = APIRouter(prefix="/findings", tags=["Findings"])


@router.get(
    "",
    response_model=List[FindingResponse],
    summary="List compliance findings"
)
def list_findings(
    severity: Optional[str] = Query(None, description="Filter by finding severity ('ERROR', 'WARNING', 'INFO')"),
    status: Optional[str] = Query(None, description="Filter by finding status ('Open', 'Resolved', etc.)"),
    rule_id: Optional[str] = Query(None, description="Filter by canonical rule code (e.g. 'TRC-001', 'RSK-002')"),
    entity_type: Optional[str] = Query(None, description="Filter by target entity type ('Requirement', 'Risk', etc.)"),
    entity_id: Optional[str] = Query(None, description="Filter by target entity ID"),
    limit: int = Query(100, ge=1, le=500, description="Page limit"),
    offset: int = Query(0, ge=0, description="Page offset"),
    db: Session = Depends(get_db)
):
    """Retrieves compliance findings generated by the deterministic engine with multidimensional filtering."""
    return FindingRepository.get_all(
        db=db,
        severity=severity,
        status=status,
        rule_violated=rule_id,
        target_entity_type=entity_type,
        target_entity_id=entity_id,
        limit=limit,
        offset=offset
    )


@router.get(
    "/{finding_id}",
    response_model=FindingResponse,
    summary="Get compliance finding by ID"
)
def get_finding(
    finding_id: str,
    db: Session = Depends(get_db)
):
    """Retrieves a single compliance finding record by primary key ID."""
    finding = FindingRepository.get_by_id(db=db, finding_id=finding_id)
    if not finding:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Compliance finding with ID '{finding_id}' not found."
        )
    return finding
